name = input ("hi, whats your name?")
print (f"hi {name}!")
input("")
subject = input ("what is your favorite school subject?")
print (f"awesome! {subject} is also my favorite subject!")
input()
print("what do you like to do for fun?")
input()
print(f"thats super cool. what do you like about it?")
input()
breakfast = input ("that sounds really great, what did you eat for breakfast today?")
print (f"crazy, i also had {breakfast} this morning!")
input()
birthday = input ("whens your birthday?")
print(f"that is so crazy, my birthday is also {birthday}!")
input()
print ("whats your favorite vacation spot?")
input()
print ("oh yea that sounds really fun, i would like to go there one day")
input()
food = input ("whats your favorite food?")
print(f"i also like {food}. my favorite food is sushi")
input()
drink = input ("whats your favorite drink?")
print (f"sick, i also like {drink} its not my favorite though. my favorite is milk.")
input()
print(f"thats all for now, thanks for talking with me {name}!")